kind:       HTTPRoute
apiVersion: gateway.networking.k8s.io/v1

metadata:
  name:      glance
  namespace: glance

spec:
  parentRefs:
    - name:        traefik-gateway
      namespace:   traefik
      sectionName: web

  hostnames:
    - glance.localhost

  rules:
    - backendRefs:
        - name: glance
          port: 8080
