kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      jellyfin
  namespace: argo-cd

spec:
  project: default
  source:
    repoURL:        https://github.com/jellyfin/jellyfin-helm
    path:           charts/jellyfin
    targetRevision: master
    # helm:
    #   values: |
    #     ingress: # KO, doesn't create any ingress
    #       main:
    #         className: nginx      # get with kubectl get ingressclass
    #         enabled: true
    #         hosts:
    #           - host: jellyfin.hp-elitedesk-800g2
    #             paths:
    #               - path: /
    #                 pathType: Prefix
    #     image:
    #       repository: jellyfin/jellyfin
    #       tag: latest

    #     service:
    #       main:
    #         type: ClusterIP
    #         port: 8096

    #     persistence:
    #       config:
    #         enabled: true
    #         mountPath: /config
    #       media:
    #         enabled: true
    #         mountPath: /media
    #         type: nfs
    #         server: 192.168.1.100
    #         path: /mnt/nfs/media

    #     resources:
    #       requests:
    #         cpu: 100m
    #         memory: 512Mi
    #       limits:
    #         cpu: 1000m
    #         memory: 1500Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
