kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      argo-cd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL:        https://argoproj.github.io/argo-helm
    chart:          argo-cd
    targetRevision: 9.1.8
    helm:
      values: |
        fullnameOverride: argo-cd
        # configs:
        #   secret:
        #     argocdServerAdminPassword: $2a$10$H1a30nMr9v2QE2nkyz0BoOD2J0I6FQFMtHS0csEg12RBWzfRuuoE6

        # releaseName: argo
        # dex:                
        #   enabled: false    # disable integration with external auth providers
        # notifications:
        #   enabled: false
        # applicationSet:
        #   enabled: false
        # server:
        #   extraArgs:
        #     - --insecure    # for Web UI over HTTP

  destination:
    server:    https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      prune:      true  # delete/prune kube resources that are no longer defined in git
      selfHeal:   true  # specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected
      allowEmpty: true  # allows deleting all application resources during automatic syncing
    syncOptions:
      - CreateNamespace=true
