app-template:
  controllers:
    sonarr:
      containers:
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.17.2952-ls313@sha256:0b3f344388bd7bed4f2f770058de795e76447e4a481b83c8d5f8fed489371fde
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 8989
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
  service:
    sonarr:
      controller: sonarr
      type: ClusterIP
      ports:
        http:
          port: 8989
        
  route:
    sonarr:
      enabled: true
      kind: HTTPRoute
      parentRefs:
        - name:        traefik-gateway
          namespace:   traefik
          sectionName: web
        - name:        traefik-gateway
          namespace:   traefik
          sectionName: websecure
      hostnames:
        - sonarr.lunics.cloud
