kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      freshrss
  namespace: argo-cd

spec:
  sources:
    - repoURL:        https://halkeye.github.io/helm-charts/
      chart:          freshrss
      targetRevision: 1.16.2
      helm:
        valueFiles:
          - $values/rss/freshrss/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      path:           rss/freshrss

  destination:
    server:    https://kubernetes.default.svc
    namespace: rss-freshrss
  
  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
