kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      glance
  namespace: argo-cd

spec:
  sources:
    - repoURL:        https://rubxkube.github.io/charts/
      chart:          glance
      targetRevision: 0.0.10
      helm:
        valueFiles:
          - $values/rss/glance/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      path:           rss/glance

  destination:
    server:    https://kubernetes.default.svc
    namespace: glance
  
  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
