preUpgradeChecker:
  jobEnabled: false   # to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.

httproute:
  enabled: true
  parentRefs:
    - name:        traefik-gateway
      namespace:   traefik
      sectionName: web
  hostnames:
    - longhorn.localhost
  path: /
  pathType: PathPrefix
  annotations: {}
