kind:       HTTPRoute
apiVersion: gateway.networking.k8s.io/v1

metadata:
  name:      freshrss
  namespace: rss

spec:
  parentRefs:
    - name:        traefik-gateway
      namespace:   traefik
      sectionName: web

  hostnames:
    - freshrss.localhost

  rules:
    - backendRefs:
        - name: freshrss
          port: 80
