kind:       Cluster
apiVersion: postgresql.cnpg.io/v1

metadata:
  name:      cluster-db-freshrss
  namespace: rss-freshrss

spec:
  instances: 1

  storage:
    size: 1Gi
  
  bootstrap:
    initdb:
      database: freshrss
      owner:    freshrss
      secret:
        name: freshrss-login
