apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-ovh-authentication
  namespace: cert-manager
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: openbao-secret-store
    kind: ClusterSecretStore
  target:
    name: ovh-authentication
  data:
  - secretKey: applicationKey
    remoteRef:
      key: ovh/application-key
      property: value
  - secretKey: applicationSecret
    remoteRef:
      key: ovh/application-secret
      property: value
  - secretKey: applicationConsumerKey
    remoteRef:
      key: ovh/consumer-key
      property: value

