apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://code.forgejo.org/forgejo-helm/forgejo-helm
    # path: /
    targetRevision: main
    # targetRevision: 13.0.0
    # chart: forgejo

    # helm:
    #   releaseName: my-forgejo
    #   values: |
    #     service:
    #       http:
    #         type: ClusterIP
    #       ssh:
    #         type: ClusterIP
    #     persistence:
    #       enabled: true
    #       existingClaim: forgejo-pvc
    #     ingress:
    #       enabled: true
    #       hosts:
    #         - host: forgejo.local
    #           paths: ["/"]
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
