qind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      heimdall
  namespace: argo-cd

spec:
  sources:
    - repoURL:        https://mitre.github.io/heimdall2-helm/
      chart:          heimdall
      targetRevision: 3.3.3
      helm:
        valueFiles:
          - $values/homepage/heimdall/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      path:           homepage/heimdall

  destination:
    server:    https://kubernetes.default.svc
    namespace: homepage
  
  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
