apiVersion: argoproj.io/v1alpha1
kind:       ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: traefik
            serverSideApply: true
          - name: gateway-api
            repoURL: https://github.com/kubernetes-sigs/gateway-api.git
            path: config/crd/experimental
            namespace: kube-system
            serverSideApply: true
          - name: sonarr
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      source:
        repoURL:        '{{ dig "repoURL"        "git@github.com:lunics/kubernetes" . }}'
        targetRevision: '{{ dig "targetRevision" "HEAD"                             . }}'
        path:           '{{ dig "path"           .name                              . }}'
      destination:
        name:      in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      syncPolicy:
        automated:
          prune:    true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "false" . | toString) }}'
