apiVersion: argoproj.io/v1alpha1
kind:       ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name:            openbao
          - name:            external-secrets
            serverSideApply: true
          - name:            cert-manager
          - name:            cert-manager-webhook-ovh
            namespace:       cert-manager
          - name:            traefik
            serverSideApply: true
          - name:            gateway-api
            repoURL:         https://github.com/kubernetes-sigs/gateway-api.git
            targetRevision:  v1.5.1
            path:            config/crd/standard
            namespace:       kube-system
            serverSideApply: true
          - name:            cloudnative-pg
            namespace:       cnpg-system
            serverSideApply: true
          - name:            sonarr
          - name:            minecraft
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      source:
        repoURL:        '{{ dig "repoURL"        "git@github.com:lunics/kubernetes" . }}'
        targetRevision: '{{ dig "targetRevision" "HEAD"                             . }}'
        path:           '{{ dig "path"           .name                              . }}'
      destination:
        name:      in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
        - group: admissionregistration.k8s.io   # required to bypass openbao-agent-injector-cfg out-of-sync
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - '.webhooks[]?.clientConfig.caBundle'
      syncPolicy:
        automated:
          prune:    true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "false" . | toString) }}'
