kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      minecraft
  namespace: argo-cd

spec:
  sources:
    - repoURL:        https://itzg.github.io/minecraft-server-charts/
      chart:          minecraft
      targetRevision: 5.0.0
      helm:
        valueFiles:
          - $values/gaming/minecraft/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      # path:           gaming/minecraft

  destination:
    server:    https://kubernetes.default.svc
    namespace: gaming-minecraft
  
  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
