kind:       Secret
apiVersion: v1

metadata:
  name:      secret-db
  namespace: rss-miniflux

type: kubernetes.io/basic-auth

stringData:
  username: miniflux
  password: miniflux
  db-string: "postgres://miniflux:miniflux@cluster-db-rw/miniflux?sslmode=disable"
    # postgres://db-user:db-password@<hostname>/<db-name>?sslmode=disable
    # db-string-format: postgres://db-user:db-password@postgresql-miniflux-rw/miniflux?sslmode=disable
  miniflux-admin:          miniflux-admin # your miniflux admin user
  miniflux-admin-password: miniflux-admin # your miniflux admin password
