forgejo:
  httpRoute:
    enabled: true
    parentRefs:
      - name:        traefik-gateway
        namespace:   traefik
        sectionName: web
      - name:        traefik-gateway
        namespace:   traefik
        sectionName: websecure
    hostnames:
      - forgejo.lunics.cloud
    matches:
      path:
        type: PathPrefix
        value: '/'

## @section Persistence
#
## @param persistence.enabled Enable persistent storage
## @param persistence.create Whether to create the persistentVolumeClaim for shared storage
## @param persistence.mount Whether the persistentVolumeClaim should be mounted (even if not created)
## @param persistence.claimName Use an existing claim to store repository information
## @param persistence.size Size for persistence to store repo information
## @param persistence.accessModes AccessMode for persistence
## @param persistence.labels Labels for the persistence volume claim to be created
## @param persistence.annotations.helm.sh/resource-policy Resource policy for the persistence volume claim
## @param persistence.storageClass Name of the storage class to use
## @param persistence.subPath Subdirectory of the volume to mount at
## @param persistence.volumeName Name of persistent volume in PVC
persistence:
  enabled: true
  create: true
  mount: true
  claimName: gitea-shared-storage
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  storageClass:
  subPath:
  volumeName: ''
  annotations:
    helm.sh/resource-policy: keep

# Configure commit/action signing prerequisites
## @section Signing
#
## @param signing.enabled Enable commit/action signing
## @param signing.gpgHome GPG home directory
## @param signing.privateKey Inline private GPG key for signed internal Git activity
## @param signing.existingSecret Use an existing secret to store the value of `signing.privateKey`
## @param signing.ssh.privateKey Inline private SSH key for signed internal Git activity
## @param signing.ssh.existingSecret Use an existing secret to store the value of `signing.ssh.privateKey`
signing:
  enabled: false
  gpgHome: /data/git/.gnupg
  privateKey: ''
  # privateKey: |-
  #   -----BEGIN PGP PRIVATE KEY BLOCK-----
  #   ...
  #   -----END PGP PRIVATE KEY BLOCK-----
  existingSecret: ''
  ssh:
    privateKey: ''
    existingSecret: ''
