kind:       Secret
apiVersion: v1

metadata:
  name:      minio-logins
  namespace: storage-minio

type: Opaque

stringData:
  config.env:
    rootUser=root
    rootPassword=root

  admin-password: adminadmin      # 8 character lenght minimum
