kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      gateway-api
  namespace: argo-cd

spec:
  project: default

  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.2.0
    path: config/crd/standard

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
