ports:
  http:                # Defines the HTTP entry point named 'web'
    port: 80
    # nodePort: 30000
    # Instructs this entry point to redirect all traffic to the 'websecure' entry point
    # redirections:
    #   entryPoint:
    #     to: websecure
    #     scheme: https
    #     permanent: true
  
  https:          # Defines the HTTPS entry point named 'websecure'
    port: 443
    exposedPort: 443
    # nodePort: 30001

api:
  dashboard: true
  insecure:  true

# ingressRoute:
#   dashboard:
#     enabled: true
#     matchRule: Host(`traefik.localhost`)
#     entryPoints:
#       - web

providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
  kubernetesIngress:
    enabled: false

gatewayClass:
  enabled: false

gateway:
  enabled: false

logs:
  access:
    enabled: true
    format:  json
    fields:
      general:
        names:
          RouterName: drop
