kind:       HTTPRoute
apiVersion: gateway.networking.k8s.io/v1

metadata:
  name:      sonarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # doesn't work across Applications

spec:
  parentRefs:
    - name:        traefik-gateway
      namespace:   traefik            # because traefik-gateway is in the traefik namespace
      sectionName: http

  hostnames:
    - "sonarr.localhost"

  rules:
    # - matches:
    #     - path:
    #         type:  PathPrefix
    #         value: /

    - backendRefs:
        - name: sonarr
          port: 8989
