apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Raw manifests you want alongside Helm output
resources:
  - httproute.yaml

# Helm chart rendered inside Kustomize
helmCharts:
  - name: sonarr
    repo: https://charts.pree.dev
    version: 1.11.0
    releaseName: sonarr
    namespace: media
