kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      root-app
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL:        git@github.com:lunics/argo-cd.git
    path:           /
    targetRevision: HEAD

  destination:
    server:    https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
