kind:       HTTPRoute
apiVersion: gateway.networking.k8s.io/v1

metadata:
  name:      homer
  namespace: homepage

spec:
  parentRefs:
    - name:        traefik-gateway
      namespace:   traefik
      sectionName: web

  hostnames:
    - homer.localhost

  rules:
    - backendRefs:
        - name: homer
          port: 8080
