kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      traefik
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io      
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default

  sources:
    - repoURL: https://traefik.github.io/charts
      chart:   traefik
      targetRevision: 38.0.0
      helm:
        valueFiles:
          - $values/infra/traefik/helm_values.yml
    - repoURL: git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref: values

  destination:
    server:    https://kubernetes.default.svc
    namespace: traefik
  
  syncPolicy:
    automated:
      enabled:  true
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
