kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      argo-workflow
  namespace: argo-cd

spec:
  source:
    chart:          argo-workflows
    repoURL:        https://argoproj.github.io/argo-helm
    targetRevision: 0.46.2
    helm:
      values: |
        fullnameOverride: argo-workflow
        crds:
          full: true

  destination:
    server:    https://kubernetes.default.svc
    namespace: argo-workflow

  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
