kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      gateway-api
  namespace: argo-cd

spec:
  source:
    repoURL:        https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: HEAD
    path:           config/crd/experimental     # standard, experimental

  destination:
    server:    https://kubernetes.default.svc
    namespace: argo-cd

  project: default

  ignoreDifferences:        # required to avoid ArgoCD injects its tracking annotation for every CRDs that exceed size
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations

  syncPolicy:
    automated:
      selfHeal: true
      prune:    true
    syncOptions:
      - CreateNamespace=true
