kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      traefik
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io      
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  sources:
    - repoURL:        https://traefik.github.io/charts
      chart:          traefik
      targetRevision: 38.0.0
      helm:
        valueFiles:
          - $values/apps/infra/traefik/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      path:           apps/infra/traefik

  destination:
    server:    https://kubernetes.default.svc
    namespace: traefik
  
  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
