kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      crossplane
  namespace: argo-cd

spec:
  source:
    repoURL:        https://charts.crossplane.io/stable
    chart:          crossplane
    targetRevision: 2.1.3
    # helm values: https://github.com/crossplane/crossplane/blob/main/cluster/charts/crossplane/values.yaml

  destination:
    server:    https://kubernetes.default.svc
    namespace: crossplane

  project: default
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
