kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      forgejo
  namespace: argo-cd

spec:
  sources:
      # only distributed via Git
    - repoURL:        https://codeberg.org/forgejo-contrib/forgejo-helm.git
      targetRevision: main
      path:           .
      # chart:          forgejo
      # targetRevision: 15.0.3
      helm:
          valueFiles:
            - $values/infra/forgejo/helm-values.yml
    - repoURL:        git@github.com:lunics/argo-cd.git
      targetRevision: HEAD
      ref:            values
      path:           infra/forgejo

  destination:
    server:    https://kubernetes.default.svc
    namespace: forgejo

  project: default
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
