kind:       Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name:      root-app
  namespace: argo-cd

spec:
  source:
    repoURL:        git@github.com:lunics/argo-cd.git
    targetRevision: HEAD
    path:           root-app
    directory:
      recurse: true

  destination:
    server:    https://kubernetes.default.svc
    namespace: argo-cd

  project: default

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
