apiVersion: argoproj.io/v1alpha1
kind:       Application
metadata:
  name:      root-app
  namespace: argo-cd
spec:
  source:
    repoURL:        git@github.com:lunics/kubernetes
    targetRevision: HEAD
    path:           infra/argo-cd/
    directory:
      recurse: true
  destination:
    name:      in-cluster
    namespace: argo-cd
  project: default
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
