image:
  repository: b4bz/homer    # image repository
  tag: ""                   # image tag
  pullPolicy: IfNotPresent  # image pull policy

env:
  TZ: UTC   # container timezone

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: false

securityContext:
  runAsUser:    1000  # user ID the application will run as
  runAsNonRoot: true
  runAsGroup:   1000  # group ID the application will run as

persistence:
  config:
    enabled:   false
    mountPath: /www/assets

configmap:
  config:
    enabled: false    # store homer configuration as a ConfigMap
    data:
      config.yml: |
        externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
