apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    chart: gitlab
    targetRevision: 7.11.2
    helm:
      releaseName: gitlab
      # values: |
      #   global:
      #     edition: ce
      #     hosts:
      #       domain: gitlab.local
      #       externalIP: ""
      #       https: false
      #     ingress:
      #       configureCertmanager: false
      #       tls:
      #         enabled: false
      #   certmanager:
      #     install: false
      #   nginx-ingress:
      #     enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
